### ISSUE TITLE
Mac 10.14 is not supported?

### ISSUE THREAD

**Issue by ahmad88me** [aboutyou/dart_packages#434]
Hi,

I have the latest version available, which is 10.14 (not 10.15). 
I got the following error when I run it:
```macos/Flutter/GeneratedPluginRegistrant.swift:13:8: error: compiling for macOS 10.14, but module 'sign_in_with_apple' has a minimum deployment target of macOS 10.15```

How can I make it work on my machine? 10.14 seems to be the latest available version for my macbook air. 

Thanks,

**Comment by ahmad88me** [comment]
I managed to make it build successfully for 10.14 

https://github.com/ahmad88me/dart_packages
