### ISSUE TITLE
Hanging on 'credential = await SignInWithApple.getAppleIDCredential' in iOS 14 simulator

### ISSUE THREAD

**Issue by tr-stan** [aboutyou/dart_packages#147]
I had my code working completely fine, but after upgrading flutter to 1.20.4 and installing xcode 12 on my mac my flutter app no longer works. It seems to be hanging on the SignInWithApple.getAppleIDCredential line once I enter my apple ID password, never obtaining the authorization code for submitting to get the access token.
relevant portion of the code:
```
try {
      print('about to get authorization code');
      credential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
        webAuthenticationOptions: WebAuthenticationOptions(
          clientId: 'my.client.id',
          redirectUri: Uri.parse(
            'https://my-site.com/callback-endpoint',
          ),
        ),
        nonce: 'example-nonce',
        state: 'example-state',
      );
  } catch (e, s) {
      print('login error: $e - stack: $s');
  }
```
The print statement at the top of the try block is printing, but the catch block doesn't catch any error after hanging for a long time, until I press the back -> cancel buttons, where it prints the expected:
`login error: NoSuchMethodError: The getter 'authorizationCode' was called on null.
Receiver: null`

I ran `flutter doctor` and have no issues. Could this package be in need of updates to be compatible with iOS 14 and xcode 12?

**Comment by HenriBeck** [comment]
Same issue as #148 

Please have a look into issue #144, at this point this isn't an issue with our library but with XCode. (See [comment](https://github.com/aboutyou/dart_packages/issues/144#issuecomment-696157418))

There hasn't been a fix discovered yet sadly
