### ISSUE TITLE
SignInWithApplePlugin.kt: (159, 29): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin

### ISSUE THREAD

**Issue by nerder** [aboutyou/dart_packages#271]
Since updating flutter to the latest available version in the channel beta we are facing an issue while trying to compile.

```
[✓] Flutter (Channel beta, 2.9.0-0.1.pre, on macOS 11.4 20F71 darwin-x64, locale en-ES)
    • Flutter version 2.9.0-0.1.pre at /Users/nerder/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (18 hours ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1
```

```
Running "flutter pub get" in checkin...
Launching lib/main_dev.dart on SM G973F in debug mode...
Running Gradle task 'assembleDevDebug'...
Note: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/share_plus-2.1.4/android/src/main/java/dev/fluttercommunity/plus/share/SharePlusPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /home/deathcode/.gradle/caches/transforms-2/files-2.1/121c56a4eb3b9888b3a925c5a1b06c22/jetified-kotlinx-coroutines-android-1.5.2.jar!/META-INF/kotlinx-coroutines-android.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /home/deathcode/.gradle/caches/transforms-2/files-2.1/86ffb183faa2bd338bfefd08560447d3/jetified-kotlin-stdlib-common-1.5.31.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /home/deathcode/.gradle/caches/transforms-2/files-2.1/8cd76d3c199ed7f84af27a672071d60c/jetified-kotlin-stdlib-jdk8-1.5.30.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /home/deathcode/.gradle/caches/transforms-2/files-2.1/9cf3398f5e61cc366c5ee0aa5c3bc390/jetified-kotlin-stdlib-jdk7-1.5.30.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /home/deathcode/.gradle/caches/transforms-2/files-2.1/9d2040e319b51dc246c400f1b2db4972/jetified-window-1.0.0-beta04-api.jar!/META-INF/window_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /home/deathcode/.gradle/caches/transforms-2/files-2.1/ab2037cf9b0bc48dddc9452783f6bf2f/jetified-kotlinx-coroutines-core-jvm-1.5.2.jar!/META-INF/kotlinx-coroutines-core.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /home/deathcode/.gradle/caches/transforms-2/files-2.1/b0053ae52ec47f3a01bcb7033b2bbe63/jetified-window-java-1.0.0-beta04-api.jar!/META-INF/window-java_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (31, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (32, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (36, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (37, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (51, 59): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (53, 6): Class 'kotlin.jvm.JvmStatic' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/jvm/JvmStatic.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (56, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (61, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (62, 31): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (67, 18): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (74, 18): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (78, 41): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (80, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (83, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (84, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (88, 31): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (89, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (95, 33): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (97, 19): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (104, 16): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (110, 10): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (111, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (115, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (119, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (123, 14): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (124, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (132, 41): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (134, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (135, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (152, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (157, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (158, 38): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (159, 29): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (161, 29): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (163, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (167, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (168, 7): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (169, 29): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (171, 11): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /home/deathcode/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.2.0/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt: (174, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /home/deathcode/.gradle/caches/transforms-2/files-2.1/246d7067bcc442dabda444cac586ac0f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sign_in_with_apple:compileDebugKotlin'.
> Compilation error. See log for more details
... (12 lines left)
```

**Comment by HenriBeck** [comment]
@nerder @deathcoder I pulled in the changes in this PR: https://github.com/aboutyou/dart_packages/pull/275

You can use this new version using the following in your pubspec:
```
sign_in_with_apple:
  git:
    url: git://github.com/aboutyou/dart_packages.git
    ref: 31b5387f2a4a17aa06e00ae385d65abcb2608850
    path: packages/sign_in_with_apple/sign_in_with_apple
```

**Comment by ultimate-tester** [comment]
Could this one please be prioritized? This is blocking new projects from using this package as the whole project cannot be build any longer when using the current version of this package.

**Comment by toureholder** [comment]
This worked for me:

1. `flutter clean`
2. Delete android/.gradle
3. Go to android/build.gradle, upgrade ext.kotlin_version to latest. In my case(1.3.5 -> 1.6.10), ext.kotlin_version = '1.6.10'

**Comment by HenriBeck** [comment]
@ultimate-tester @nerder does the same issue also exist for flutter projects using `2.10`?

**Comment by HenriBeck** [comment]
I guess it will also not work in Flutter 2.10 since it also has this breaking change: https://docs.flutter.dev/release/breaking-changes/kotlin-version

**Comment by ultimate-tester** [comment]
> I guess it will also not work in Flutter 2.10 since it also has this breaking change: https://docs.flutter.dev/release/breaking-changes/kotlin-version

Exactly, doesn't work. But the fix is close by because the PR is working perfectly for me. It's a matter of accepting it to make it work again :)

**Comment by realappie** [comment]
When you don't even use sign_in_with_apple in android but spend hours on this build error 🥲 Is there anyway to ignore it for android builds if you don't use it anyway?

**Comment by ultimate-tester** [comment]
> When you don't even use sign_in_with_apple in android but spend hours on this build error 🥲 Is there anyway to ignore it for android builds if you don't use it anyway?

That would be interesting, I have the same scenario where I only use the package on iOS.

**Comment by nerder** [comment]
I guess that this should be closed now, I'm using the latest version of the `sign_in_with_apple` and I'm not facing the issue anymore.
